### ISSUE TITLE
Storefront Performance and UI Alignment Issues

### ISSUE THREAD

**Issue by chillpilllike** [rigby-sh/solace-medusa-starter#104]
Thank you for creating such an awesome and visually appealing design!

However, I’ve noticed a few performance and UI issues that I wanted to bring to your attention:
	1.	Performance Lag with Large Datasets:
	•	Issue: The storefront operates smoothly with a limited number of products. However, when the product catalog grows, the collection pages, shop pages, and product pages experience significant slowdowns and take longer to load.
	•	Example: https://secretgreen-medusa-soloace-storefront.g5edov.easypanel.host
	
	2.	Unaligned Product Titles:
	•	Issue: Product titles with longer text appear misaligned within the grid layout, affecting the overall aesthetics and readability.
	•	Question: How can we adjust the styling to ensure that long product titles are properly aligned and maintain a consistent appearance across all product grids?

I appreciate your assistance in addressing these concerns and look forward to any recommendations or solutions you might have.

I have a bare-metal dedicated server with 64 CPU cores and 256GB of RAM, its utilization rarely exceeds 5%.

<img width="1318" alt="Screenshot 2024-11-28 at 12 47 26 pm" src="https://github.com/user-attachments/assets/2e7ea7c1-be29-4210-b0b5-8526d73f9779">

<img width="1295" alt="Screenshot 2024-11-28 at 12 47 20 pm" src="https://github.com/user-attachments/assets/8fbec1e8-9e2f-4479-9ef1-f3b999de94de">

**Comment by agnwoj99** [comment]
Hi @chillpilllike, we will investigate into this problem and will get back to you soon 😊

**Comment by chillpilllike** [comment]
Thanks, I have tested the store with 2 different backends, one with 10k products and another one with 50k, the lags are equal in both.

**Comment by agnwoj99** [comment]
Hi @chillpilllike,
Following up with an answer regarding the UI issue:

To ensure the grid always maintains the same structure, you'll need to add the `h-full` class to the main `Box` in the `ProductTileClient` component. Additionally, apply `flex-1 justify-between` to the div that wraps the product title and price.
To demonstrate this, I added a shadow to highlight the edges of the tile:
<img width="1249" alt="Zrzut ekranu 2024-11-29 o 19 36 20" src="https://github.com/user-attachments/assets/e692609f-d948-45a9-ba4a-7f3b500d3fc2">

To fix the issue related to the title length, you need to remove the classes from the link that wraps it.
Also, we currently limit it to two lines using the `line-clamp-2` class in the `ProductInfo` component. If you'd like the entire title to display, you can simply remove that class.

Hopefully, this resolves the issue for this component! Let me know if you need further assistance 😊

**Comment by KamilNahotko** [comment]
@chillpilllike Hey, regarding the performance issue with large datasets – we’ve made significant improvements in the latest update. The product listings, including collection pages, shop pages, and product pages, should now load much faster, even with a large catalog.

Please update your Storefront to the latest version and let us know if everything is running smoothly on your end now. If you’re still seeing any lag, feel free to reach out again!

**Comment by chillpilllike** [comment]
Thank you so much for all the time and effort you’ve dedicated to this project. The load time has improved significantly, dropping from about 25-30 seconds to 7-11 seconds. This is a great achievement!

<img width="790" alt="Screenshot 2024-12-03 at 4 55 14 pm" src="https://github.com/user-attachments/assets/d29863d5-ac8a-4991-a702-c8aaaa351688">


<img width="794" alt="Screenshot 2024-12-03 at 4 55 48 pm" src="https://github.com/user-attachments/assets/526142a6-2d80-44c2-b2b5-da84415e6d72">


<img width="788" alt="Screenshot 2024-12-03 at 4 56 23 pm" src="https://github.com/user-attachments/assets/ce2f35f7-4eea-4fb4-a7ee-e26359395117">


Observations and Issues Noticed:


1.	Load Times:
	•	Product pages without related products load in 7-9 seconds.
	•	Product pages with related products take 10-12 seconds.

2.	Add-to-Cart Experience:
	•	Clicking “Add to Cart” triggers the notification popup instantly, but the product is only added to the cart after   
                4-5 seconds, leading to a poor user experience.

3.	Cart Dropdown:
	•	Product titles in the cart dropdown overflow outside the boundary and should be truncated for a cleaner    
                appearance.

<img width="474" alt="Screenshot 2024-12-03 at 4 40 06 pm" src="https://github.com/user-attachments/assets/566b523c-ffbd-4e30-9a68-daf48107236c">


4.	Product Descriptions:
	•	Line breaks in the product descriptions are being removed, causing the text to appear as a single paragraph. This affects readability and professionalism. The theme code should preserve line breaks to display the descriptions tidily and professionally.



5.	Search Functionality:
	•	The search feature throws the following error. The theme should be optimized to support Meilisearch indexes, especially for handling large datasets efficiently:

Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 3547501988

Error: Response error. Status: 500
    at n (/app/.next/server/chunks/5398.js:1:188901)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async q (/app/.next/server/app/[countryCode]/(main)/results/[query]/page.js:1:3774) {
  digest: '3547501988'
}

Once again, I sincerely appreciate your hard work. I hope to see even further speed optimizations in the future. Thank you for your dedication and efforts!

**Comment by KamilNahotko** [comment]
@chillpilllike Thank you so much for your valuable feedback and your continued support of the project. We’re glad to hear that the load times have improved significantly, and we truly appreciate your observations.

Regarding the issues you’ve raised:

- Cart and Add-to-Cart Experience: We’re happy to confirm that the issues with the cart have been resolved, and the experience should now be smoother.

- Optimizations: We’re continuously working on optimizations to ensure the best performance, especially when handling large product datasets. Our team is actively working on further improving load times and performance.

- Meilisearch: Unfortunately, the Medusa plugin for Meilisearch does not yet support Medusa 2.0. We are closely monitoring the situation, and as soon as there are updates or a new version that supports Medusa 2.0, we will implement it.

Thank you again for your efforts and patience. We’re committed to making the project even better and will keep improving the speed and functionality over time!
