### ISSUE TITLE
error filter-products-atributes

### ISSUE THREAD

**Issue by justinelut** [rigby-sh/solace-medusa-starter#89]
I have setup medusa 2.0 stable server, but while using this template to fetch data from it, i click on the categories i have created i get an error in the getStoreFilters function
![image](https://github.com/user-attachments/assets/7afbfddb-98ec-4f0b-9757-f761a12979dd)
is the api updated, or there is something i need to add on the medusa server?

**Comment by umersaleem50** [comment]
I managed to solve this, you need to add missing routes into your medusa admin api (Medusajs v2 Admin) under /src/api/search folder.

Follow these steps:

1. Copy the folder from [Repo Link](https://github.com/rigby-sh/solace-medusa-starter-api/tree/main/src/api/store).
2. Copy the Middlewares file from [Repo Link](https://github.com/rigby-sh/solace-medusa-starter-api/tree/main/src/api).
3. You may need to install zod for validation.


_Alternative: I will suggest you to use this medusa admin api [Repo Link](https://github.com/rigby-sh/solace-medusa-starter-api/tree/main), as it's already configured for solace nextjs storefront._

**Comment by justinelut** [comment]
@umersaleem50 thank you for this.. i will try it out, i believe it is what was missing in the readme

**Comment by justinelut** [comment]
Hello @umersaleem50 , do you have the fix for the orders page not showing what a customer has bought,
![image](https://github.com/user-attachments/assets/4fb07751-3eae-4363-b3b4-4c11efa6443e) ... i have completed many purchases but am getting no orders in the dashboard

**Comment by agnwoj99** [comment]
@justinelut this problem is related to request error on update cart in Medusa 2.0: https://docs.medusajs.com/resources/storefront-development/cart/update#update-carts-customer
Despite passing in the body `customer_id` as in the documentation, unfortunately the request throws an error, like u see below: 
<img width="813" alt="Postman request" src="https://github.com/user-attachments/assets/7014f013-1ed2-4dff-a2c8-0802376c109f">

You can following this open issue on Medusa GitHub here: https://github.com/medusajs/medusa/issues/9755
And the information about the main element of this thread actually escaped us in the documentation - we will add it soon, thank for catching it 😊

**Comment by umersaleem50** [comment]
@justinelut @agnwoj99 I managed to fix it by doing the following steps:

1. Make a new Medusa 2.0 Admin Project with the latest updates (Let's call it "Admin Updated" for reference)
2. Copy all the files of /src/api folder of solace admin and paste it into /src/api/ folder of your "Admin Updated" project.
3. Copy all Medusa config file of solace admin into the "Admin Updated" project. (you can modify it according to docs)
4. And then you will able to see all the orders.

**How to fix local storage issue, in case you're not using S3.**
1. `{
    resolve: "@medusajs/medusa/file",
    options: {
      providers: [
        {
          resolve: "@medusajs/medusa/file-local",
          id: "local",
          options: {
            upload_dir: "static",
            backend_url: process.env.LOCAL_STORAGE_URL,
            // provider options...
          },
        },
      ],
    },
  },` Make sure to add local-file module (in case you're not using S3 for storage)

2. Add the following image remote Patterns into your storefront (Solace Storefront) `{
        protocol: "https", //make sure your app is using https otherwise change it to http
        hostname: process.env.MEDUSA_BACKEND_STORAGE_URL, //don't add http:// or https:// just place hostname ie. yourstore.com
      },`
3. Declare the value of MEDUSA_BACKEND_STORAGE_URL in your .env file and that's it.

How to fix strapi images if they are not loading on Storefront?
1. Add the following image remote Patterns into your storefront (Solace Storefront) ` {
        protocol: "https", // make sure your app is using https otherwise change it to http
        hostname: process.env.STRAPI_HOST_URL, // don't add http:// or https:// just place hostname ie. cms.yourstore.com
      },`
2. Declare the value of STRAPI_HOST_URL in your .env file and that's it.

You can DM on my LinkedIn in case you need help: https://www.linkedin.com/in/umersaleem50/
