### ISSUE TITLE
Upgrade related dependency packages

### ISSUE THREAD

**Issue by fuxianwei** [rigby-sh/solace-medusa-starter#99]
The versions of some dependency packages are too late. Upgrade the dependency packages

<img width="1329" alt="截屏2024-11-13 22 24 49" src="https://github.com/user-attachments/assets/d1c611c5-9f32-43b6-a724-1b895435b7ee">

**Comment by agnwoj99** [comment]
Hello @fuxianwei, forgive the delay in responding. The packages have just been updated 😊🚀
